language: java
jdk:
  - oraclejdk11
node_js: "10.16.3"
sudo: false

services:
  - docker

env:
  - DOCKER_COMPOSE_FILE=docker/docker-compose.yml

cache:
  directories:
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/jars-2
    - $HOME/.gradle/caches/jars-3
    - $HOME/.gradle/caches/modules-2/files-2.1/
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
    - $HOME/build/RADAR-base/radar-upload-source-connector/radar-upload-frontend/node_modules/

before_install:
  - docker-compose --version

install:
  - cd radar-upload-frontend/ && npm install && cd ..
  - ./gradlew assemble

script:
  - ./gradlew check --stacktrace
  - cd radar-upload-frontend/ && npm run test:unit
  - cd ../
  - sudo docker-compose -f $DOCKER_COMPOSE_FILE up -d && sleep 90 && ./gradlew integrationTest --stacktrace
  - sudo docker-compose -f $DOCKER_COMPOSE_FILE down
