language: java
jdk:
  - oraclejdk11
sudo: false

services:
  - docker

env:
  - DOCKER_COMPOSE_FILE=integration-test/src/integrationTest/docker/docker-compose.yml

cache:
  directories:
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/jars-2
    - $HOME/.gradle/caches/jars-3
    - $HOME/.gradle/caches/modules-2/files-2.1/
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

before_install:
  - docker-compose --version

script:
  - ./gradlew check
  - sudo docker-compose -f $DOCKER_COMPOSE_FILE up -d && sleep 90 && ./gradlew integrationTest
  - sudo docker-compose -f $DOCKER_COMPOSE_FILE down
