#alpine version close to the version mentioned in the readme
FROM node:10.16.3-alpine as builder

RUN mkdir /app
WORKDIR /app

COPY ./radar-upload-frontend/package*.json /app/
RUN npm install

COPY ./radar-upload-frontend/ /app/

RUN npm run build --prod


FROM nginx:1.17.3-alpine

# add init script
COPY ./docker/nginx.conf /etc/nginx/nginx.conf

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/dist/ .

# expose internal port:80 and run init.sh
EXPOSE 80
