---
version: '3.9'

services:

  #---------------------------------------------------------------------------#
  # Management Portal                                                         #
  #---------------------------------------------------------------------------#
  managementportal-app:
    image: radarbase/management-portal:2.1.0
    depends_on:
      - radarbase-postgresql
    ports:
      - "8090:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SERVER_CONTEXT_PATH: /managementportal
#      ZUUL_ROUTES_MANAGEMENT_PORTAL_URL: http://localhost:8080/managementportal/oauth
      SPRING_DATASOURCE_URL: jdbc:postgresql://radarbase-postgresql:5432/managementportal
      SPRING_DATASOURCE_USERNAME: radarcns
      SPRING_DATASOURCE_PASSWORD: radarcns
      MANAGEMENTPORTAL_FRONTEND_CLIENT_SECRET: "testMe"
      MANAGEMENTPORTAL_COMMON_BASE_URL: http://localhost:8080/managementportal
      MANAGEMENTPORTAL_COMMON_MANAGEMENT_PORTAL_BASE_URL: http://localhost:8080/managementportal
      MANAGEMENTPORTAL_OAUTH_CLIENTS_FILE: /mp-includes/config/oauth_client_details.csv
      MANAGEMENTPORTAL_CATALOGUE_SERVER_ENABLE_AUTO_IMPORT: 'false'
      MANAGEMENTPORTAL_OAUTH_SIGNING_KEY_ALIAS: 'radarbase-managementportal-ec'
      JAVA_OPTS: -Xmx256m  # maximum heap size for the JVM running ManagementPortal, increase this as necessary
    volumes:
      - ../etc/mp-config/:/mp-includes/config
    healthcheck:
      test: "curl -f http://localhost:8080/managementportal/oauth/token -d grant_type=client_credentials -d client_id=radar_upload_test_client -d client_secret=test"
      start_period: 20s

  radarbase-postgresql:
    image: postgres:16
    environment:
      - POSTGRES_USER=radarcns
      - POSTGRES_PASSWORD=radarcns
      - POSTGRES_DB=managementportal

  radarbase-upload:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=radarcns
      - POSTGRES_PASSWORD=radarcns
      - POSTGRES_DB=uploadconnector

  sftp-server:
    image: emberstack/sftp
    ports:
      - "2222:22"
    volumes:
      - ./src/integrationTest/resources/sftp.json:/app/config/sftp.json:ro

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    command:
      - server
      - /data
