baseUri: "http://0.0.0.0/radar-upload/"
managementPortalUrl: "http://managementportal-app:8080/managementportal/"
jdbcDriver: "org.postgresql.Driver"
jdbcUrl: "jdbc:postgresql://radarbase-postgresql:5432/uploadconnector"
jdbcUser: "radarcns"
jdbcPassword: "radarcns"
additionalPersistenceConfig:
  "hibernate.dialect": "org.hibernate.dialect.PostgreSQL95Dialect"
sourceTypes:
  - name: "phone-acceleration"
    topics:
      - "android_phone_acceleration"
    contentTypes:
      - "text/csv"
    timeRequired: false
    sourceIdRequired: false
    configuration:
      "setting1": "value1"
      "setting2": "value2"
